# @ Created with PyCharm Community Edition
# @ Author KeShiFu
# @ Date 2023/03/19
# @ Time 21:16

from Lib.Play import Play
from time import sleep
from Lib.MusicScore import MusicScore

# 刻师傅格式
test_ke = """0.5
(NZ)Z/CN/AD/A(DN)/
(MZ)X/MS/GS/MS/
ZC/AD/AD/GD/
ZC/AD/AD/GD/

(NZ)Z/CN/AD/AN/
(MZ)X/MS/GS/MS/
ZC/AD/AD/GD/
ZC/AD/AD/GD/

(NZ)Z/(EC)(QN)/(EZ)(EC)/M(EA)/
(MZ)X/(WM)(WB)/MX/(QA)(EM)/
(VZ)(NZ)/ZV/(NZ)Z/VN/
(VZ)(ANZ)/(DZ)(GV)/QJ/GD/

(NZ)Z/(EC)(QN)/(EZ)(EC)/M(EA)/
(MZ)X/(WM)(WB)/MB/(QA)(QM)/
Z(EBZ)/ZB/LZ/BM/
Z(BZ)/ZC/LM/LA/

(AVZ)(NZ)/(QZ)(QV)/(QNZ)Z/(WV)W/
(BZ)(MZ)/(GB)X/(GB)(MZ)/(DX)M/
(JCZ)(BZ)/(JX)(MZ)/(GC)(MZ)/(GX)G/
(NZ)(HZ)/(QC)N/LB/(HN)(GA)/

(QVZ)(NZ)/(HZ)(HV)/(NZ)(GZ)/VA/
(QBZ)(MZ)/(HB)(HX)/B(GMZ)/S(GM)/
Z(HC)/(QG)D/CB/GJ/
ZC/B(EQ)/E/E/

(QVZ)(NZ)/ZV/ZM/(TV)T/
(BZ)(MZ)/B(DX)/B(EMZ)/(EX)E/
(TCZ)(BZ)/(TX)(MZ)/(TC)(YMZ)/XE/
(RGSNZ)E(WZ)L/(TC)(EDN)/ZB/(WN)(EA)/


(EVZ)(NZ)/Z(WV)/(NZ)Z/(WV)(EA)/
(EGBZ)(MZ)/B(WX)/B(MZ)/XM/
(EDZ)C/BS/(EC)B/(TD)J/
(QDZ)C/B(EQ)/(EG)D/(ES)D/

(QVZ)(NZ)/ZV/ZM/(TV)T/
(BZ)(MZ)/B(DX)/B(EMZ)/(EX)E/
(TCZ)(BZ)/(TX)(MZ)/(TC)(YMZ)/XE/
(RGSNZ)E(WZ)L/(TC)(EDN)/ZB/(WN)(EA)/

(EVZ)(NZ)/Z(WV)/(NZ)Z/(WV)(EA)/
(EGBZ)(MZ)/B(WX)/B(EMZ)/XM/
(EAZ)C/BS/(EC)B/(TG)J/
(QDZ)/L/L/L/
(ENZ)(AZ)/C(DN)/(AC)H/(JN)(QN)/

(WMZ)X/M(EX)/L(JS)/(QM)(WS)/
(EZ)C/A(JD)/AD/(QG)(WD)/
(TZ)C/A(ED)/AD/J(QD)/
(ENZ)Z/C(DN)/AH/(JC)(QN)/

(WMZ)X/M(ES)/L(JS)/(QM)(WS)/
(QZ)C/A(JD)/LD/GJ/
(QDZ)C/AD/SD/SA/
(DNZ)Z/(EC)(QN)/(EA)(EC)/M(EA)/

(GMZ)X/(WM)(WB)/MX/(QA)(EM)/
(VZ)(NZ)/ZV/(NZ)Z/VN/
(VZ)(ANZ)/(DZ)(GV)/QJ/(GV)(DA)/
(DNZ)Z/(EC)(QN)/(EZ)(EC)/M(EA)/

(GMZ)X/(WM)(WB)/MX/(QA)(QM)/
Z(EBZ)/ZB/LZ/B(MX)/
(XZ)(CBZ)/ZC/LM/L(VG)/
(GVZ)(NZ)/(QZ)(QV)/(QANZ)Z/(WV)L(WV)X/

(GBZ)(MZ)/(GB)L/(GB)L(MZ)G/XLD(MZ)/
(JGCZ)(BZ)/(JX)(MZ)/(JC)(MZ)/(GX)LG(CZ)/
(ANZ)(HZ)/(QC)N/CB/(HN)LL(GC)ZL/
(QGVZ)(NZ)/(HZ)(HBV)/(NZ)(GZ)/BLLLVXL/

(QGBZ)(MZ)/(HB)(HX)/B(GMZ)/S(GM)/
Z(HZ)/(QC)(DM)/CB/(GB)J/
ZC/B(EQ)/E/AB(EC)LZLZL/

(QGVZ)/Z(GBV)/Z(MBV)/(TGBV)L(TBZ)(XZ)/
(SMBZ)/(MZ)(DABX)/(BX)(EMZ)/(EBX)E/
(TGDCZ)(BZ)/(TMZ)(SBXMZ)/(TBX)(YMZ)/(SBX)LL(EBZ)(CZ)L/

(RGDANZ)EWL/T(EDANC)/CB/(WNC)LL(EVZ)ZL/
(EGAVZ)/Z(WANV)/V(AN)/(WANV)LL(EBZ)(XZ)L/
(EGABZ)M/X(WSABX)/X(AB)/(MBX)LLZ(BZ)L/

(EDAZ)/C(SMB)/(EA)(GC)/(TMB)(GBZ)/
(QDAZ)(BZ)/Z(EDAB)/(EGA)(DZ)/(ESAB)D/
(QGFAVZ)/Z(ABV)/Z(MV)/(TABV)LL(TBZ)(XZ)L/
(SMBZ)/(MZ)(DABX)/(BC)(EMZ)/(ESBX)LL(ESX)(MZ)L/

(TDACZ)(BZ)/(TS)(ABX)/T(YX)/(SMBX)LL(EBZ)(CZ)L/
(RGSNZ)E(WNZ)L/T(EDANCZ)/Z(BC)/(WNCZ)LL(EAVZ)ZL/
(EGAVZ)/Z(WAV)/ZB/(WGABV)LL(EBZ)(XZ)L/

(EGABZ)/X(WMBX)/B(EX)/(MBX)LLZ(BZ)L/
(EGAZ)Z/B(SBCZ)/E(DB)/(TGCZ)J/
(QBGZ)/L/L/WE/
(EAV)(NZ)/Z(WV)/LZ/(WV)(EA)/

(EGB)(MZ)/B(WM)/L(EMZ)/XM/
(EDA)C/BS/(EA)(DB)/(TGC)J/
(QGDABZ)/L/L/L/
"""

# 呱呱格式
test_gua = """53
VAW-E-T-Q- W-BSE-T-Q- 
NDW-E-T-Y- W-BSE-H-Q-
VAW-E-T-Q-W-BSE-T-Q- 
NDW-E-T-Y-W-BSE-H-Q-

ZVDW-DE-DT-DQ-DW-XBDE-T-DQ-
CNWS-SE-ST-SY-WS-ZBSE-SH-SQ-
ZVDW-DE-DT-DQ-DW-XBDE-T-DQ-
CNWS-SE-ST-SY-SW-ZBDE-D-G-

VADH+GQ-W-N-BJ-MSG-F-
NAD-G-GJ-Q-N-Z-ADGQ-J-
VAH+GQ+NJ-BG-MS-G-
NAD-S-BS-S-NS-ZS-ZCBSD-SG-

VADH+GQ-W-N-BJ-MSG-F-
NAD-G-GJ-Q-N-Z-ADGQ-J-
VAH+GQ+NJ-BG-MSG-H-
NAD-S-BS-S-NS-ZS-ZCBSH-SJ-

VADQ-=AD-V=ADGJ-H-BGJ-ADGQ-B-
ND-GJ=AD=H=N=ADGJ-HQ-AGJ-ADG-AH-
VADG-ZA=CB=A=V=ZCBH-DG-BA-NS-BAD-
CN-S=ZCB=S=N=ZS-S-AS-ASH-ZSJ-

VADQ-D-D-ADJ-DH=ZCB=ADJ-BDQ-D-
CNS-SJ-SH-ASGJ-SQ=AD=WS-ZADE-RF-
ZVNA-AQ-BAQ-DE-NSW-AQ-ADQ+
ZCA+++DE-GT=ED=

VAW-VQ=N=ADH=Q-ADW-B=MSG-BDE=MSG=T=E=
NDHW-Q=N=ADG=Q-ADQ-C=ADG-E=ADG=T=E=
VAFW-V=N=ADE=GT-ADGT==BHY=MSG-MSGT=R=E-
NDH-W=HE=ADGT=Y=E=ADW=E-ZA-ADGE=ZA=GT=DE=

VAW-VQ=N=ADH=Q-ADW-B=MSG-BDE=MSG=T=E=
NDHW-Q=N=ADG=Q-ADQ-C=ADG-AQ=ADGMJ=NH=MJ=
VAFH-V=N=ADW-=AD=J=B=H-MSGJ-MGJ-
V-ZAQ-BAG-X-NAD-N=AZ=C=B=N=A=

VAW-E-T-Q- W-BSE-T-Q- 
NDW-E-T-Y- W-BSE-H-Q-
VAW-E-T-Q-W-BSE-DT-DQ- 
NASW-SE-ST-SQ-SW-SE+Q=W=

VNAE-W=Q=NADQ-H=J=Q-BMSJ=H=BG-BD=G=
NADH-J=Q=ADJ=G=G=H=G-ZBA-CD=D=ZG=G=
VNAH-J=Q=NADJ-Q=W=E-BMSW=Q=MJ-BG=G=
NAD-Q=W=ADE-W=DE=T=Y=ZE=W=AD-ZQ=W=

VNAE-W=Q=NADQ-H=J=Q-BMSJ=H=BG-BD=G=
NADH-J=Q=ADJ=G=G=H=G-ZBA-NH-Z=G=
VNA-FH-NAD=HQ-=W-BMS=QE=BMS-BJW-
NAD=HQ-=CNA-N-A=S=DA=B=AG=S=CD-

VAFHQEY-V=A=FHT-R=FH=DE-B-MSGW=DE=BFR-
NDH=ED=NSW=AQ=DG=SW=ED=DGE==DE=ZSW=AQ=ZCB=NH=ZMJ=AQ=
VAF=MJ=VNH=BAG=VN-G=VN=FH-B=HQ=MSG-BGJ-
ND=DG=N=A=CBAD-=CBDH=N=A=ZS=D=CBG=H=Q=W=

VAFHQEY-V=A=FHT-R=FH=DE-B-MSGW=DE=BFR-
DH-AD-ADQE=JW=ADQE-AD-AD-ZBMS-MS-
VAD-AD-AD-ADWR-ADQE-ADJW-BSGQ-AQ-

VAD-V=N=AD-V=NAD-V=NAD-V-DA-
VASD-V=N=AD-V=NAD-V=NAD-V-DA-
BASG-GB=AG=SG=G=BG=SG=H=H=BH=H=SGQ=Q=BAQ=AQ=
BSGW=WS=BSW=SW=BDGE=DE=BDE=DE=BGT=GT=BGT=GT=DE-TG=ED=

VAW-VQ=N=ADH=Q-ADW-B=MSG-BDE=MSG=T=E=
NDHW-Q=N=ADG=Q-ADQ-C=ADG-E=ADG=T=E=
VAFW-V=N=ADE=GT-ADGT==BHY=MSG-MSGT=R=E-
NDH-W=HE=ADGT=Y=E=ADW=E-ZA-ADGE=ZA=GT=DE=

VAW-VQ=N=ADH=Q-ADW-B=MSG-BDE=MSG=T=E=
NDHW-Q=N=ADG=Q-ADQ-C=ADG-AQ=ADGMJ=NH=MJ=
VAFH-V=N=ADW-=AD=J=B=G-MD-MGJ-
V-AQ=Z=BADHQ-X-NDH-N=N=ADSG=H=D=N=

VAF-T-GQE=W=Q=W=W-VAG-D=VS=A=S=
VAF-T-GQE=W=Q=W=W-VAG-D=VS=A=S=
BSG-T-GJE=W=Q=W=W-BMG-D=BS=A=S=
XB-Y-JET=E=E=T=T-BMH-G=BD=BD=BG=

NDH-T-HQE=Q=Q=W=W-NAG-D=NA=A=NS=
NDH-T-HQE=Q=Q=W=W-NAG-D=NA=A=NS=
MGJ-T-GJE=Q=Q=W=W-AQ=SW=ED-RF-
BSG-XSGJT-XSGJT-BGJT-BGJT++

VAW-E-T-Q- W-BSE-T-Q- 
NDW-E-T-Y- W-BSE-H-Q-
VAW-E-T-Q-W-BSE-T-Q- 
NDW-E-T-Y-W-BSE-H-Q-

VAHW-E-TQ-AW-V-JE-BMTG-FQ-
NADW-EG-JT-YQ-W-ZE-QH-J-
VAHW-E-QT-A-VJW-GE-BSGT-GQ-
NADW-E-T-Y-W-ZE-ADH-GQ-

VAHW-E-TQ-AW-V-JE-BMTG-FQ-
NADW-EG-JT-YQ-W-ZE-QH-J-
VAHW-E-QT-A-VJW-G-BSG-GQ-
BGW-S-BGQ-S-BGJ-S-DE-GT=ED=

VAW-VQ=N=ADH=Q-ADW-B=MSG-BDE=MSG=T=E=
NDHW-Q=N=ADG=Q-ADQ-C=ADG-E=ADG=T=E=
VAFW-V=N=ADE=GT-ADGT==BHY=MSG-MSGT=R=E-
NDH-W=HE=ADGT=Y=E=ADW=E-ZA-ADGE=ZA=GT=DE=

VAW-VQ=N=ADH=Q-ADW-B=MSG-BDE=MSG=T=E=
NDHW-Q=N=ADG=Q-ADQ-C=ADG-AQ=ADGMJ=NH=MJ=
VAFH-V=N=ADW-=AD=J=B=H-MSGJ-MGJ-
V-ZAQ-BAG-X-NAD-N=AZ=C=B=N=A=

VNADH-V=N=ADBG=HN=NQA=AD=WS-BSG-SGE=B=Q-
NADHQ-N=A=DGE=SW=QA=DG=SW-CD-ADGT=C=E-
VADGQE-V=N=ADQ=MJ=NG=AD=NH-BSG-SG=B=F-
NADG-QN=AW=DGE-AW=DGE=R=W=ZAE=R=DGT=AY=ZE=W=

VNADH-V=N=ADBG=HN=NQA=AD=WS-BSG-SGE=B=Q-
NADHQ-N=A=DGE=SW=QA=DG=SW-CD-ADGT=C=E-
VAFHQEY-V=N=AD-NDE=AD=SJW-BSG-SG=B=AQ=WS=
VDHE-A-BG-SW=AQ=NDHQ-A=S=DN=ZS=CD=BG=

VNADH-V=N=ADBG=HN=NQA=AD=WS-BSG-SGE=B=Q-
NADHQ-N=A=DGE=SW=QA=DG=SW-CD-ADGT=C=E-
VADGQE-V=N=ADQ=MJ=NG=AD=NH-BSG-SG=B=F-
NADG-QN=AW=DGE-AW=DGE=R=W=ZAE=R=DGT=AY=ZE=W=

VNADH-V=N=ADBG=HN=NQA=AD=WS-BSG-SGE=B=Q-
NADHQ-N=A=DGE=SW=QA=DG=SW-CD-ADGT=C=E-
VAFHQEY-V=N=AD-NDE=AD=SJW-BSG-SG=B=AQ=WS=
VDHE-A-BG-SW=AQ=NDHQ-N=A=D=G=H=Q=

VAW-E-T-Q- W-BSE-T-Q- 
NDW-E-T-Y- W-BSE-H-Q-
VAW-E-T-Q-W-BSE-T-Q- 
NDW-E-T-Q-W-=E+Q+W
"""
text = MusicScore.guaToke(test_gua)  # 测试呱呱谱
# text = MusicScore.formatKe(test_ke)  # 测试刻师傅谱
# 循环测试几次
for i in range(1):
    sleep(3)
    print("\n第{}次测试".format(i + 1))
    play = Play()
    play.start(text, 1)  # 开始
    sleep(10)
    play.suspend_continue()  # 暂停
    sleep(3)
    play.suspend_continue()  # 继续
    sleep(10)
    play.finish()  # 结束
